name: Mirror to gitlab
on:
  push:
    branches:
      - '**'
jobs:
  mirroring:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Mirror repository 
      uses: jakob-fritz/github2lab_action@main
      env:
        MODE: 'mirror'
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        FORCE_PUSH: "true"
        GITLAB_HOSTNAME: ${{ secrets.GITLAB_URL }}
        GITLAB_PROJECT_ID: "1053"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
